baseURL: "https://ogceylon.github.io/"
title: "OGCEYLON"
languageCode: "en-us"
paginate: 5
theme: "PaperMod"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

googleAnalytics: "G-E7L5P3HRTQ"

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: "OGCEYLON"
  description: "Just a blog :)"
  keywords: [Blog, General, Linux, Windows, Android]
  author: "OGC"
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true
  enableJSONLD: true

  assets:
    disableFingerprinting: true
    favicon: "/images/favicon/favicon.ico"
    favicon16x16: "/images/favicon/favicon-16x16.png"
    favicon32x32: "/images/favicon/favicon-32x32.png"
    apple_touch_icon: "/images/favicon/apple-icon.png"
    safari_pinned_tab: "/images/favicon/apple-icon.png"
  
  label:
    text: "OGCEYLON"
    icon: /images/favicon/favicon-32x32.png
    iconHeight: 35

  profileMode:
    enabled: false
    title: "OGCEYLON"
    subtitle: "Just a blog :)"
    imageUrl: "https://avatars.githubusercontent.com/u/82071300?v=4"
    imageWidth: 200 
    imageHeight: 200
    imageTitle: github profile pic
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  homeInfoParams:
    Title: "OGCEYLON 👋"
    Content: Just a blog :)

  socialIcons:
    - name: github
      url: "https://github.com/ogceylon"
    - name: youtube
      url: "https://youtube.com/@ogceylon"
    - name: tiktok
      url: "https://tiktok.com/@ogceylon"
    - name: telegram
      url: "https://t.me/ogceylon"
    # - name: facebook
    #   url: "https://facebook.com/ogceylon"

  analytics:
    google:
      SiteVerificationTag: "G-E7L5P3HRTQ"

  cover:
    hidden: false
    hiddenInList: false
    hiddenInSingle: true

  editPost:
    URL: "https://github.com/ogceylon/ogceylon.github.io/content"
    Text: "Suggest Changes"
    appendFilePath: true

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: search
      name: Search
      url: /search/
      weight: 5
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 10
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 15
    - identifier: archive
      name: Archive
      url: /archives/
      weight: 20
    - identifier: about
      name: About
      url: /about/
      weight: 30

pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    style: monokai

outputs:
  home:
    - HTML
    - RSS
    - JSON
### How to create a new post using hugo commands?
# hugo new --kind post posts/General/Post-Title.md